name: CI

on: [push, pull_request]

jobs:
  minitest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5-alpine
        env:
          POSTGRES_USER: runner
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:5.0.6-alpine
        ports: ['6379:6379']
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install --yes libpq-dev
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 17.4.0

      - name: Set up gems cache
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-
      - name: Set up node_modules cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --without rubocop --jobs 4 --retry 3
      - name: Install Node dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
      - name: Set up database
        run: bundle exec rake db:setup
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

      - name: Run tests
        run: bundle exec rails test:system test
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Set up gems cache
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubocop-
      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --without default development test brakeman --jobs 4 --retry 3
      - name: Run rubocop
        run: bundle exec rubocop --parallel

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 17.4.0

      - name: Set up node_modules cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-prettier-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-prettier-
      - name: Install Node dependencies
        run: npm install prettier --no-package-lock --save-exact

      - name: Run prettier
        run: npm run prettier:check
